name: Run Tests for UI Ingredients

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 9.7.0
      - run: pnpm install
      - working-directory: packages/ui-ingredients
        run: pnpm test
